metanorma/isodoc

Gemfile.lock

- https://github.com/metanorma/isodoc/issues/89

Remove ruby-xslt dependency

---

lib/isodoc/function/to_word_html.rb

- metanorma/mn-templates-iso#4

metanorma/mn-templates-iso#4 Fix image path calculation on Windows OS

---

Gemfile

- https://github.com/metanorma/metanorma-release/issues/1

Update Gemfile to allow 'override' gems with Gemfile.devel which will be generated by release-tool

---

lib/isodoc/function/references.rb
spec/isodoc/postproc_spec.rb
spec/isodoc/ref_spec.rb

Do not use ISBN or ISSN identifiers to cross-reference books

---

isodoc.gemspec

- affect https://github.com/metanorma/mn-templates-itu/pull/27

Restrict liquid to continue support Ruby 2.4

---

.github/workflows/rake.yml
isodoc.gemspec

- #258
- metanorma/metanorma-build-scripts#58

proof-of-concept for GH composite actions

---

lib/isodoc/convert.rb
lib/isodoc/pdf_convert.rb
lib/isodoc/xslfo_convert.rb
spec/isodoc/xslfo_convert_spec.rb

- metanorma/bipm-si-brochure#108

Add target_pdf method to reduce code duplication

---

lib/isodoc/xslfo_convert.rb
spec/isodoc/xslfo_convert_spec.rb

PDF encryption: https://github.com/metanorma/metanorma/issues/224

---

lib/isodoc/presentation_function/terms.rb

code refactor of concept_render

---

lib/isodoc/presentation_function/section.rb
spec/isodoc/section_spec.rb

floating title: https://github.com/metanorma/metanorma-bsi/issues/95

---

lib/isodoc/presentation_function/section.rb
lib/isodoc/xref/xref_sect_gen.rb

refactor: https://github.com/metanorma/metanorma-bsi/issues/80

---

lib/isodoc/presentation_function/image.rb
spec/isodoc/blocks_spec.rb

- https://github.com/metanorma/metanorma-standoc/issues/573

#573 raise error if inkscape not found in PATH

---

lib/isodoc/xslfo_convert.rb
spec/isodoc/xslfo_convert_spec.rb

#374 Add --syntax-highlight argument for mn2pdf

---

isodoc.gemspec
lib/isodoc/i18n.rb

refactor isodoc-i18n

---

isodoc.gemspec
lib/isodoc/convert.rb
lib/isodoc/function/inline.rb
lib/isodoc/function/references.rb
lib/isodoc/function/to_word_html.rb
lib/isodoc/html_function/postprocess.rb
lib/isodoc/presentation_function/section.rb
lib/isodoc/presentation_xml_convert.rb
lib/isodoc/word_function/postprocess.rb
lib/isodoc/word_function/table.rb
lib/isodoc/xref.rb
lib/isodoc/xref/xref_anchor.rb
lib/isodoc/xref/xref_sect_gen.rb
lib/relaton/render/config.yml
lib/relaton/render/general.rb
spec/isodoc/blocks_spec.rb
spec/isodoc/i18n_spec.rb
spec/isodoc/inline_spec.rb
spec/isodoc/ref_spec.rb

span processing: https://github.com/metanorma/metanorma-iso/issues/595

---

lib/isodoc/gem_tasks.rb
spec/isodoc/gem_tasks_spec.rb

#403 fix css generation logic, not rely on CLEAN global FileList

---

lib/isodoc/function/inline.rb
spec/isodoc/inline_spec.rb

span/style: https://github.com/metanorma/metanorma-standoc/issues/647

---

lib/isodoc-yaml/i18n-fr.yaml

i18n-fr.yaml updated for #446

---

isodoc.gemspec
lib/isodoc/presentation_function/inline.rb
spec/isodoc/presentation_xml_spec.rb

erefstack: https://github.com/metanorma/metanorma-standoc/issues/691

---

isodoc.gemspec
lib/isodoc/convert.rb
lib/isodoc/function/references.rb
lib/isodoc/function/to_word_html.rb
lib/isodoc/presentation_function/inline.rb
lib/isodoc/presentation_function/xrefs.rb
spec/isodoc/inline_spec.rb

xref style=id: https://github.com/metanorma/metanorma-standoc/issues/692

---

isodoc.gemspec

chore: cleanup isodoc version include

---

lib/isodoc/presentation_function/terms.rb
spec/isodoc/inline_spec.rb

concept/@bold:  https://github.com/metanorma/metanorma-bsi/issues/162

---

isodoc.gemspec
lib/isodoc/function/section.rb
lib/isodoc/function/to_word_html.rb
lib/isodoc/presentation_function/section.rb
lib/isodoc/xref/xref_sect_gen.rb
spec/isodoc/section_spec.rb

colophon: https://github.com/metanorma/metanorma-bsi/issues/241

---

lib/isodoc/convert.rb
lib/isodoc/init.rb
lib/isodoc/presentation_function/bibdata.rb
lib/isodoc/presentation_function/sourcecode.rb
spec/isodoc/presentation_xml_spec.rb

preprocess-xslt: https://github.com/metanorma/metanorma-ogc/issues/522

---

Gemfile.devel
lib/isodoc/presentation_function/block.rb

refactor: https://github.com/metanorma/metanorma-ogc/issues/495

---

lib/isodoc/html_function/postprocess.rb

See https://github.com/metanorma/metanorma-utils/issues/27

More Vectory

---

lib/isodoc/presentation_function/xrefs.rb
spec/isodoc/xref_format_spec.rb

xref label: https://github.com/metanorma/metanorma-iso/issues/1141

---

Gemfile.devel
lib/isodoc/function/blocks.rb
spec/isodoc/table_spec.rb

test table/dl: https://github.com/metanorma/metanorma-plateau/issues/58

---

lib/isodoc/xref/xref_gen_seq.rb

refactor: https://github.com/metanorma/mn-samples-jis/issues/39

---

Gemfile.devel
isodoc.gemspec

dependency relaton-render 0.9

---

lib/isodoc/base_style/scripts.html

Fix for TOC from Yablokov

---

lib/isodoc/base_style/scripts.html

From @yablokov:
Fixes metanorma/metanorma-standoc#953

Fix: Correct Table of Contents margin when toggling visibility

---

lib/isodoc/function/table.rb
lib/isodoc/word_function/table.rb
spec/isodoc/sourcecode_spec.rb
spec/isodoc/table_spec.rb

table styling: https://github.com/metanorma/metanorma/issues/446

---

lib/isodoc/function/table.rb
lib/isodoc/presentation_function/block.rb
lib/isodoc/word_function/lists.rb
lib/isodoc/word_function/table.rb
spec/isodoc/blocks_spec.rb
spec/isodoc/figures_spec.rb
spec/isodoc/table_spec.rb

table style: https://github.com/metanorma/metanorma-standoc/issues/1048

---

lib/isodoc/function/cleanup.rb
lib/isodoc/function/table.rb
lib/isodoc/html_function/html.rb
lib/isodoc/word_function/table.rb
spec/isodoc/sourcecode_spec.rb
spec/isodoc/table_spec.rb

plain tables: https://github.com/metanorma/metanorma-jis/issues/101
